### ISSUE TITLE
Add support for WSL2

### ISSUE THREAD

**Issue by gianni-rg** [kf5i/k3ai#18]
It would be interesting to be able to setup and run K3AI on Windows + WSL2, for local dev/test box. Are there any plans?

**Comment by alfsuse** [comment]
### Is your feature request related to a problem? Please describe.
We are looking for an initial interest in having k3ai supported withing WSL2 (CPU and GPU) so that users may experiment locally.

### Describe the solution you'd like
user should launch something like:

 ```SHELL 
bash -c "k3ai commands"
``` 
and get as a result a full working environment on their laptops

### Additional context
Please contribute with comments and feedback here so we will know if this need to be prioritized
